// Writes seed.sql: demo data for the D1 database.
//
// The seed is plain SQL rather than a script that calls the API, so it can be
// applied with `wrangler d1 execute` against either the local or the remote
// database. Timestamps are computed by SQLite at apply time, so the ledger
// always spans the month leading up to whenever it was seeded.
//
//   node scripts/generate-seed.mjs
//
// Quantities are chosen so that five lines finish at or under their reorder
// point, and so that no issue or transfer ever overdraws a location — the same
// rule the API enforces.

import { writeFileSync } from 'node:fs';

const LOCATIONS = [
  { id: 1, code: 'WH-A', name: 'Jurong Warehouse', kind: 'warehouse' },
  { id: 2, code: 'WH-B', name: 'Changi Overflow', kind: 'warehouse' },
  { id: 3, code: 'ST-1', name: 'Orchard Shopfront', kind: 'store' },
];

/** `opening` is received once; `issue` goes out on each of four days. */
const ITEMS = [
  { id: 1,  sku: 'BLT-M6-30',    name: 'Hex bolt M6 x 30mm',      category: 'Fasteners',   unit: 'box of 100', cost: 480,  reorder: 20, opening: 60,  issue: 10 },
  { id: 2,  sku: 'NUT-M6',       name: 'Hex nut M6',              category: 'Fasteners',   unit: 'box of 200', cost: 320,  reorder: 20, opening: 70,  issue: 12 },
  { id: 3,  sku: 'WSH-M6',       name: 'Flat washer M6',          category: 'Fasteners',   unit: 'box of 500', cost: 260,  reorder: 10, opening: 50,  issue: 10 },
  { id: 4,  sku: 'CBL-CAT6-05',  name: 'Cat6 patch cable 0.5m',   category: 'Cabling',     unit: 'each',       cost: 190,  reorder: 40, opening: 120, issue: 20 },
  { id: 5,  sku: 'CBL-CAT6-30',  name: 'Cat6 patch cable 3m',     category: 'Cabling',     unit: 'each',       cost: 420,  reorder: 40, opening: 140, issue: 22 },
  { id: 6,  sku: 'CBL-TIE-200',  name: 'Cable tie 200mm',         category: 'Cabling',     unit: 'bag of 100', cost: 350,  reorder: 15, opening: 60,  issue: 10 },
  { id: 7,  sku: 'PSU-12V-5A',   name: 'Power supply 12V 5A',     category: 'Power',       unit: 'each',       cost: 2150, reorder: 8,  opening: 30,  issue: 5 },
  { id: 8,  sku: 'BAT-18650',    name: 'Li-ion cell 18650',       category: 'Power',       unit: 'each',       cost: 780,  reorder: 24, opening: 90,  issue: 15 },
  { id: 9,  sku: 'FUS-5A',       name: 'Blade fuse 5A',           category: 'Power',       unit: 'pack of 10', cost: 240,  reorder: 12, opening: 48,  issue: 9 },
  { id: 10, sku: 'ENC-IP65-S',   name: 'Enclosure IP65 small',    category: 'Enclosures',  unit: 'each',       cost: 1640, reorder: 6,  opening: 20,  issue: 4 },
  { id: 11, sku: 'ENC-IP65-L',   name: 'Enclosure IP65 large',    category: 'Enclosures',  unit: 'each',       cost: 3120, reorder: 4,  opening: 12,  issue: 3 },
  { id: 12, sku: 'LBL-THERM-50', name: 'Thermal label roll 50mm', category: 'Consumables', unit: 'roll',       cost: 590,  reorder: 10, opening: 40,  issue: 8 },
];

const RESTOCKS = [
  { sku: 'ENC-IP65-S', quantity: 25 },
  { sku: 'ENC-IP65-L', quantity: 25 },
];

const STORE_TRANSFERS = [
  { sku: 'CBL-CAT6-05', quantity: 12 },
  { sku: 'CBL-CAT6-30', quantity: 12 },
  { sku: 'BAT-18650', quantity: 12 },
  { sku: 'FUS-5A', quantity: 6 },
];

const ISSUE_DAYS = [21, 14, 7, 2];

const WAREHOUSE = 1;
const OVERFLOW = 2;
const STORE = 3;

const quote = (value) => (value === null ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`);

/** SQLite computes the timestamp when the seed is applied, not when generated. */
const now = "strftime('%Y-%m-%dT%H:%M:%SZ', 'now')";
const daysAgo = (days, hour) =>
  `strftime('%Y-%m-%dT%H:%M:%SZ', datetime('now', '-${days} days', 'start of day', '+${hour} hours'))`;

const itemBySku = (sku) => {
  const item = ITEMS.find((candidate) => candidate.sku === sku);
  if (item === undefined) throw new Error(`unknown seed sku ${sku}`);
  return item;
};

const lines = [
  '-- Demo data for crud-app. Generated by scripts/generate-seed.mjs — edit that,',
  '-- not this file.',
  '--',
  '--   wrangler d1 execute crud-app-db --local  --file=./seed.sql',
  '--   wrangler d1 execute crud-app-db --remote --file=./seed.sql',
  '--',
  '-- Applying this REPLACES the contents of all three tables.',
  '',
  'DELETE FROM movements;',
  'DELETE FROM items;',
  'DELETE FROM locations;',
  '',
];

for (const location of LOCATIONS) {
  lines.push(
    'INSERT INTO locations (id, code, name, kind, created_at, updated_at) VALUES ' +
      `(${location.id}, ${quote(location.code)}, ${quote(location.name)}, ${quote(location.kind)}, ${now}, ${now});`,
  );
}
lines.push('');

for (const item of ITEMS) {
  lines.push(
    'INSERT INTO items (id, sku, name, category, unit, unit_cost_cents, reorder_point, created_at, updated_at) VALUES ' +
      `(${item.id}, ${quote(item.sku)}, ${quote(item.name)}, ${quote(item.category)}, ${quote(item.unit)}, ` +
      `${item.cost}, ${item.reorder}, ${now}, ${now});`,
  );
}
lines.push('');

let count = 0;
const movement = (itemId, locationId, kind, quantity, reference, note, occurredAt, group = null) => {
  count += 1;
  lines.push(
    'INSERT INTO movements (item_id, location_id, kind, quantity, reference, note, transfer_group, occurred_at, created_at) VALUES ' +
      `(${itemId}, ${locationId}, ${quote(kind)}, ${quantity}, ${quote(reference)}, ${quote(note)}, ` +
      `${quote(group)}, ${occurredAt}, ${now});`,
  );
};

lines.push('-- Opening stock, four weeks back.');
for (const item of ITEMS) {
  movement(item.id, WAREHOUSE, 'receipt', item.opening, 'PO-1041', 'Opening stock', daysAgo(28, 8));
}

lines.push('', '-- A steady trickle out of the warehouse against work orders.');
ITEMS.forEach((item, index) => {
  ISSUE_DAYS.forEach((day, round) => {
    movement(item.id, WAREHOUSE, 'issue', -item.issue, `WO-${2200 + index * 4 + round}`, null, daysAgo(day, 11));
  });
});

lines.push('', '-- Mid-month replenishment of the slow, expensive lines.');
for (const restock of RESTOCKS) {
  movement(itemBySku(restock.sku).id, WAREHOUSE, 'receipt', restock.quantity, 'PO-1088', 'Replenishment', daysAgo(10, 10));
}

lines.push('', '-- Transfers: two rows each, sharing a transfer_group.');
STORE_TRANSFERS.forEach((transfer, index) => {
  const group = `tr_seed_store_${index + 1}`;
  const item = itemBySku(transfer.sku);
  movement(item.id, WAREHOUSE, 'transfer_out', -transfer.quantity, 'TR-004', 'Weekly store replenishment', daysAgo(6, 14), group);
  movement(item.id, STORE, 'transfer_in', transfer.quantity, 'TR-004', 'Weekly store replenishment', daysAgo(6, 14), group);
});

const bolts = itemBySku('BLT-M6-30');
movement(bolts.id, WAREHOUSE, 'transfer_out', -10, 'TR-005', 'Freeing rack space in Jurong', daysAgo(4, 15), 'tr_seed_overflow');
movement(bolts.id, OVERFLOW, 'transfer_in', 10, 'TR-005', 'Freeing rack space in Jurong', daysAgo(4, 15), 'tr_seed_overflow');

lines.push('', '-- A stocktake write-down: the stock is gone, but nothing took it.');
movement(bolts.id, WAREHOUSE, 'adjustment', -2, 'STK-DEMO', 'Water damage found during stocktake', daysAgo(1, 16));

lines.push('');

writeFileSync(new URL('../seed.sql', import.meta.url), lines.join('\n'), 'utf8');
console.log(`seed.sql: ${LOCATIONS.length} locations, ${ITEMS.length} items, ${count} movements`);
